[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_2022_pumpfun = "GY4gideNhYWJLkgxDW7q9hS6U2SrKb9AmSUbJPsWhEKB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=650bb4db-b1d0-4641-b7e1-afdea19a34c9"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-2022-pumpfun.ts"
