[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_2022_pumpfun = "GY4gideNhYWJLkgxDW7q9hS6U2SrKb9AmSUbJPsWhEKB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=e2cc6225-fae1-4f90-a6b1-5684f49dec62"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-2022-pumpfun.ts"
